### ISSUE TITLE
Provide the unzipped files on GitHub, not the zip?

### ISSUE THREAD

**Issue by peterjc** [simonerighi/ExperimentSchools2017#1]
I would suggest there is more value in recording the unzipped oTree files on GitHub, than in the single compressed file. Doing this will allow easy searching and browsing of the experiment contents, and give a meaningful change history.

(Confusingly there appears to be a git repository inside the zip file, perhaps in error?)

**Comment by simonerighi** [comment]
too many files in the folder. it doens't allow me to upload them.

**Comment by peterjc** [comment]
Ah - were you trying to upload via the GitHub website? I would suggest using the git command line for this.
